FROM node:13.10-alpine

WORKDIR /src/app

COPY ./dist /dist
COPY ./entrypoint.sh /entrypoint.sh
RUN apk add curl

HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD curl --fail http://localhost:3001/health || exit 1

ENTRYPOINT ["sh", "/entrypoint.sh"]

CMD ["node", "/dist/api.bundle.js"]