FROM node:13.10-alpine

WORKDIR /src/app

COPY ./dist .
RUN apk add curl

HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD curl --fail http://localhost:3002/health || exit 1

CMD ["sh", "-c", "node api.bundle.js DOMAIN=${DOMAIN} CORS=${CORS}"]